### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by mech** [thegarage/thor-rails#7]
Hi, was wondering if thor-rails is compatible with Rails 5.1. I am having this issues:

`gems/railties-5.1.1/lib/rails/commands/console/console_command.rb:85:in 'perform': uninitialized constant Thor::Rails::Console (NameError)`

**Comment by sallesma** [comment]
I am experiencing the same issue.

No problem with Rails 5.0, it appears when upgrading to 5.1

Here is the stacktrace:
```
$ rails s -b 0.0.0.0
/home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:130:in `block in perform': undefined method `application' for Thor::Rails:Module (NoMethodError)
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /home/sallesma/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

@mech have you found any solution ?

**Comment by mech** [comment]
Unfortunately I have not have any luck. Switching back to rake.
